max_cpu : 4

refresh_interval: 300 #seconds

default_error_image: "images/no-signal.jpg"

server :
    port: 8080

cameras :
  - name: "Carpark"
    url: "http://192.168.1.112:8080/video3.mjpg"
    path: "north_west_eight_antiques"
    error_image: "images/no-signal-toc.jpg"

  - name: "Camera 2"
    url: "http://96.10.1.168/mjpg/1/video.mjpg"
    path: "cam2"
    error_image: "images/no-signal-toc.jpg"

  - name:
    url: "http://plazacam.studentaffairs.duke.edu/mjpg/video.mjpg"
    path: "cam3"
    error_image: "images/no-signal-toc.jpg"

#  - name: "Kamera 4"
#    url: "http://plaza232323cam.studentaffairs.duke.edu/mjpg/video.mjpg"
#    path: "cam4"