max_cpu : 4

image_update_interval: 300 #seconds

status_update_interval: 5 #seconds

default_error_image: "images/no-signal.jpg"

server :
    port: 8080
    public_address: "217.35.86.6"

cameras :
  - name: "Carpark"
    url: "http://192.168.1.112:8080/video3.mjpg"
    path: "carpark"
    error_image: "images/no-signal-toc.jpg"

  - name: "16 - North West Eight Antiques"
    url: "http://192.168.1.107:8080/video3.mjpg"
    path: "north_west_eight_antiques"
    error_image: "images/no-signal-toc.jpg"

  - name: "31 - Tony Sinclair"
    url: "http://192.168.1.113:8080/video3.mjpg"
    path: "tony_sinclair"
    error_image: "images/no-signal-toc.jpg"

  - name: "41 - Antiques By Design"
    url: "http://192.168.1.115:8080/video3.mjpg"
    path: "antiques_by_design"
    error_image: "images/no-signal-toc.jpg"

  - name: "54 - Carol Fotheringham"
    url: "http://192.168.1.108:8080/video3.mjpg"
    path: "carol_fotheringham"
    error_image: "images/no-signal-toc.jpg"

  - name: "24 - Gazelles of Lyndhurst"
    url: "http://192.168.1.106:8080/video3.mjpg"
    path: "gazelles_of_lyndhurst_2"
    error_image: "images/no-signal-toc.jpg"

  - name: "14 - Dappr Aviation"
    url: "http://192.168.1.102:8080/video3.mjpg"
    path: "dappr_aviation"
    error_image: "images/no-signal-toc.jpg"

  - name: "24 - Gazelles of Lyndhurst"
    url: "http://192.168.1.101:8080/video3.mjpg"
    path: "gazelles_of_lyndhurst_1"
    error_image: "images/no-signal-toc.jpg"

  - name: "23 - Brian Hawkins"
    url: "http://192.168.1.103:8080/video3.mjpg"
    path: "brian_hawkins"
    error_image: "images/no-signal-toc.jpg"

  - name: "4 - Gwilym Davies"
    url: "http://192.168.1.109:8080/video3.mjpg"
    path: "gwilym_davies"
    error_image: "images/no-signal-toc.jpg"

  - name: "9 - Liz Callingham"
    url: "http://192.168.1.105:8080/video3.mjpg"
    path: "liz_callingham"
    error_image: "images/no-signal-toc.jpg"

  - name: "Ground Floor"
    url: "http://192.168.1.118:8080/video3.mjpg"
    path: "ground_floor"
    error_image: "images/no-signal-toc.jpg"

  - name: "60 - Ines Cole"
    url: "http://192.168.1.120:8080/video3.mjpg"
    path: "ines_cole"
    error_image: "images/no-signal-toc.jpg"

  - name: "5 - Martin"
    url: "http://192.168.1.114:8080/video3.mjpg"
    path: "martin_1"
    error_image: "images/no-signal-toc.jpg"

  - name: "13 - David Edmonds"
    url: "http://192.168.1.117:8080/video3.mjpg"
    path: "david_edmonds"
    error_image: "images/no-signal-toc.jpg"

  - name: "10 - Omnipod"
    url: "http://192.168.1.116:8080/video3.mjpg"
    path: "omnipod"
    error_image: "images/no-signal-toc.jpg"

  - name: "5 - Hallway"
    url: "http://192.168.1.131:8080/video3.mjpg"
    path: "hallway"
    error_image: "images/no-signal-toc.jpg"

  - name: "TEST TEST"
    url: "http://96.10.1.168/mjpg/1/video.mjpg"
    path: "test"
    error_image: "images/no-signal-toc.jpg"