max_cpu : 8

image_update_interval: 300 #seconds

status_update_interval: 5 #seconds

default_error_image: "images/no-signal.jpg"

server :
    port: 8080
    public_address: "localhost:8080"

    cameras :
        - name: "Carpark"
          mjpeg_url: "http://192.168.1.112:8080/video3.mjpg"
          url_path: "carpark"
          error_image: "images/no-signal-toc.jpg"

        - name: "16 - North West Eight Antiques"
          mjpeg_url: "http://192.168.1.107:8080/video3.mjpg"
          url_path: "north_west_eight_antiques"
          error_image: "images/no-signal-toc.jpg"

        - name: "31 - Tony Sinclair"
          mjpeg_url: "http://192.168.1.113:8080/video3.mjpg"
          url_path: "tony_sinclair"
          error_image: "images/no-signal-toc.jpg"

        - name: "41 - Antiques By Design"
          mjpeg_url: "http://192.168.1.115:8080/video3.mjpg"
          url_path: "antiques_by_design"
          error_image: "images/no-signal-toc.jpg"

        - name: "54 - Carol Fotheringham"
          mjpeg_url: "http://192.168.1.108:8080/video3.mjpg"
          url_path: "carol_fotheringham" error_image:
              "images/no-signal-toc.jpg"

        - name: "24 - Gazelles of Lyndhurst" mjpeg_url:
            "http://192.168.1.106:8080/video3.mjpg" url_path:
                "gazelles_of_lyndhurst_2" error_image:
                    "images/no-signal-toc.jpg"

        - name: "14 - Dappr Aviation" mjpeg_url:
            "http://192.168.1.102:8080/video3.mjpg" url_path: "dappr_aviation"
          error_image: "images/no-signal-toc.jpg"

        - name: "24 - Gazelles of Lyndhurst"
          mjpeg_url: "http://192.168.1.101:8080/video3.mjpg"
          url_path: "gazelles_of_lyndhurst_1"
          error_image: "images/no-signal-toc.jpg"

        - name: "23 - Brian Hawkins"
          mjpeg_url: "http://192.168.1.103:8080/video3.mjpg"
          url_path: "brian_hawkins"
          error_image: "images/no-signal-toc.jpg"

        - name: "4 - Gwilym Davies"
          mjpeg_url: "http://192.168.1.109:8080/video3.mjpg"
          url_path: "gwilym_davies"
          error_image: "images/no-signal-toc.jpg"

        - name: "9 - Liz Callingham"
          mjpeg_url: "http://192.168.1.105:8080/video3.mjpg"
          url_path: "liz_callingham"
          error_image: "images/no-signal-toc.jpg"

        - name: "Ground Floor"
          mjpeg_url: "http://192.168.1.118:8080/video3.mjpg"
          url_path: "ground_floor"
          error_image: "images/no-signal-toc.jpg"

        - name: "60 - Ines Cole"
          mjpeg_url: "http://192.168.1.120:8080/video3.mjpg"
          url_path: "ines_cole"
          error_image: "images/no-signal-toc.jpg"

        - name: "5 - Martin"
          mjpeg_url: "http://192.168.1.114:8080/video3.mjpg"
          url_path: "martin_1"
          error_image: "images/no-signal-toc.jpg"

        - name: "13 - David Edmonds"
          mjpeg_url: "http://192.168.1.117:8080/video3.mjpg"
          url_path: "david_edmonds"
          error_image: "images/no-signal-toc.jpg"

        - name: "10 - Omnipod"
          mjpeg_url: "http://192.168.1.116:8080/video3.mjpg"
          url_path: "omnipod"
          error_image: "images/no-signal-toc.jpg"

        - name: "5 - Hallway"
          mjpeg_url: "http://192.168.1.131:8080/video3.mjpg"
          url_path: "hallway"
          error_image: "images/no-signal-toc.jpg"

        - name: "TEST 2"
          mjpeg_url: "http://96.10.1.168/mjpg/1/video.mjpg"
          url_path: "test2"
          error_image: "images/no-signal.jpg"


        - name: "TEST 1"
          mjpeg_url: "http://plazacam.studentaffairs.duke.edu/mjpg/video.mjpg"
          url_path: "test1"
          error_image: "images/no-signal.jpg"
